
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return Promise.all([
        knex('products').insert({ id: 1, product_name: 'Asparagus', price_in_cents: 520 }),
        knex('products').insert({ id: 2, product_name: 'Broccoli', price_in_cents: 195 }),
        knex('products').insert({ id: 3, product_name: 'Carrot', price_in_cents: 3 }),
        knex('products').insert({ id: 4, product_name: 'Cauliflower', price_in_cents: 974 }),
        knex('products').insert({ id: 5, product_name: 'Celery', price_in_cents: 700 }),
        knex('products').insert({ id: 6, product_name: 'Corn', price_in_cents: 822 }),
        knex('products').insert({ id: 7, product_name: 'Cucumber', price_in_cents: 371 }),
        knex('products').insert({ id: 8, product_name: 'Lettuce', price_in_cents: 296 }),
        knex('products').insert({ id: 9, product_name: 'Mushroom', price_in_cents: 444 }),
        knex('products').insert({ id: 10, product_name: 'Onion', price_in_cents: 863 }),
        knex('products').insert({ id: 11, product_name: 'Pepper', price_in_cents: 666 }),
        knex('products').insert({ id: 12, product_name: 'Potatoe', price_in_cents: 683 }),
        knex('products').insert({ id: 13, product_name: 'Spinach', price_in_cents: 163 }),
        knex('products').insert({ id: 14, product_name: 'Squash', price_in_cents: 577 }),
        knex('products').insert({ id: 15, product_name: 'Zucchini', price_in_cents: 751 }),
        knex('products').insert({ id: 16, product_name: 'Tomatoe', price_in_cents: 942 }),
        knex('products').insert({ id: 17, product_name: 'Apple', price_in_cents: 775 }),
        knex('products').insert({ id: 18, product_name: 'Avocado', price_in_cents: 730 }),
        knex('products').insert({ id: 19, product_name: 'Banana', price_in_cents: 169 }),
        knex('products').insert({ id: 20, product_name: 'Berry', price_in_cents: 351 }),
        knex('products').insert({ id: 21, product_name: 'Cherry', price_in_cents: 104 }),
        knex('products').insert({ id: 22, product_name: 'Grapefruit', price_in_cents: 831 }),
        knex('products').insert({ id: 23, product_name: 'Grape', price_in_cents: 983 }),
        knex('products').insert({ id: 24, product_name: 'Kiwi', price_in_cents: 775 }),
        knex('products').insert({ id: 25, product_name: 'Lemon', price_in_cents: 946 }),
        knex('products').insert({ id: 26, product_name: 'Melon', price_in_cents: 609 }),
        knex('products').insert({ id: 27, product_name: 'Nectarine', price_in_cents: 430 }),
        knex('products').insert({ id: 28, product_name: 'Orange', price_in_cents: 903 }),
        knex('products').insert({ id: 29, product_name: 'Peache', price_in_cents: 691 }),
        knex('products').insert({ id: 30, product_name: 'Pear', price_in_cents: 274 }),
        knex('products').insert({ id: 31, product_name: 'Plum', price_in_cents: 174 }),
        knex('products').insert({ id: 32, product_name: 'Bagel', price_in_cents: 423 }),
        knex('products').insert({ id: 33, product_name: 'Egg', price_in_cents: 556 }),
        knex('products').insert({ id: 34, product_name: 'Hummus', price_in_cents: 727 }),
        knex('products').insert({ id: 35, product_name: 'Tofu', price_in_cents: 489 }),
        knex('products').insert({ id: 36, product_name: 'Tortilla', price_in_cents: 609 }),
        knex('products').insert({ id: 37, product_name: 'Burrito', price_in_cents: 555 }),
        knex('products').insert({ id: 38, product_name: 'Pizza', price_in_cents: 305 }),
        knex('products').insert({ id: 39, product_name: 'Gravy', price_in_cents: 823 }),
        knex('products').insert({ id: 40, product_name: 'Honey', price_in_cents: 827 }),
        knex('products').insert({ id: 41, product_name: 'Jam', price_in_cents: 508 }),
        knex('products').insert({ id: 42, product_name: 'Ketchup', price_in_cents: 992 }),
        knex('products').insert({ id: 43, product_name: 'Mayonnaise', price_in_cents: 545 }),
        knex('products').insert({ id: 44, product_name: 'Relish', price_in_cents: 716 }),
        knex('products').insert({ id: 45, product_name: 'Salsa', price_in_cents: 507 }),
        knex('products').insert({ id: 46, product_name: 'Syrup', price_in_cents: 553 }),
        knex('products').insert({ id: 47, product_name: 'Cereal', price_in_cents: 3 }),
        knex('products').insert({ id: 48, product_name: 'Coffee', price_in_cents: 499 }),
        knex('products').insert({ id: 49, product_name: 'Pancake', price_in_cents: 638 }),
        knex('products').insert({ id: 50, product_name: 'Pasta', price_in_cents: 496 }),
        knex('products').insert({ id: 51, product_name: 'Rice', price_in_cents: 714 }),
        knex('products').insert({ id: 52, product_name: 'Tea', price_in_cents: 875 }),
        knex('products').insert({ id: 53, product_name: 'Vinegar', price_in_cents: 193 }),
        knex('products').insert({ id: 54, product_name: 'Applesauce', price_in_cents: 142 }),
        knex('products').insert({ id: 55, product_name: 'Broth', price_in_cents: 300 }),
        knex('products').insert({ id: 56, product_name: 'Olive', price_in_cents: 467 }),
        knex('products').insert({ id: 57, product_name: 'Tuna', price_in_cents: 43 }),
        knex('products').insert({ id: 58, product_name: 'Soup', price_in_cents: 472 }),
        knex('products').insert({ id: 59, product_name: 'Tomato', price_in_cents: 175 }),
        knex('products').insert({ id: 60, product_name: 'Basil', price_in_cents: 769 }),
        knex('products').insert({ id: 61, product_name: 'Cilantro', price_in_cents: 871 }),
        knex('products').insert({ id: 62, product_name: 'Cinnamon', price_in_cents: 512 }),
        knex('products').insert({ id: 63, product_name: 'Garlic', price_in_cents: 379 }),
        knex('products').insert({ id: 64, product_name: 'Ginger', price_in_cents: 159 }),
        knex('products').insert({ id: 65, product_name: 'Mint', price_in_cents: 596 }),
        knex('products').insert({ id: 66, product_name: 'Parsley', price_in_cents: 406 }),
        knex('products').insert({ id: 67, product_name: 'Salt', price_in_cents: 307 }),
        knex('products').insert({ id: 68, product_name: 'Butter', price_in_cents: 219 }),
        knex('products').insert({ id: 69, product_name: 'Milk', price_in_cents: 357 }),
        knex('products').insert({ id: 70, product_name: 'Yogurt', price_in_cents: 919 }),
        knex('products').insert({ id: 71, product_name: 'Feta', price_in_cents: 254 }),
        knex('products').insert({ id: 72, product_name: 'Bacon', price_in_cents: 935 }),
        knex('products').insert({ id: 73, product_name: 'Beef', price_in_cents: 987 }),
        knex('products').insert({ id: 74, product_name: 'Chicken', price_in_cents: 78 }),
        knex('products').insert({ id: 75, product_name: 'Ham', price_in_cents: 829 }),
        knex('products').insert({ id: 76, product_name: 'Crab', price_in_cents: 531 }),
        knex('products').insert({ id: 77, product_name: 'Lobster', price_in_cents: 997 }),
        knex('products').insert({ id: 78, product_name: 'Oyster', price_in_cents: 965 }),
        knex('products').insert({ id: 79, product_name: 'Salmon', price_in_cents: 447 }),
        knex('products').insert({ id: 80, product_name: 'Shrimp', price_in_cents: 404 }),
        knex('products').insert({ id: 81, product_name: 'Tilapia', price_in_cents: 887 }),
        knex('products').insert({ id: 82, product_name: 'Beer', price_in_cents: 808 }),
        knex('products').insert({ id: 83, product_name: 'Champagne', price_in_cents: 146 }),
        knex('products').insert({ id: 84, product_name: 'Gin', price_in_cents: 481 }),
        knex('products').insert({ id: 85, product_name: 'Juice', price_in_cents: 920 }),
        knex('products').insert({ id: 86, product_name: 'Whiskey', price_in_cents: 37 }),
        knex('products').insert({ id: 87, product_name: 'Vodka', price_in_cents: 926 }),
        knex('products').insert({ id: 88, product_name: 'Cake', price_in_cents: 460 }),
        knex('products').insert({ id: 89, product_name: 'Donut', price_in_cents: 336 }),
        knex('products').insert({ id: 90, product_name: 'Flour', price_in_cents: 436 }),
        knex('products').insert({ id: 91, product_name: 'Sugar', price_in_cents: 642 }),
        knex('products').insert({ id: 92, product_name: 'Candy', price_in_cents: 77 }),
        knex('products').insert({ id: 93, product_name: 'Oatmeal', price_in_cents: 829 }),
        knex('products').insert({ id: 94, product_name: 'Popcorn', price_in_cents: 596 }),
        knex('products').insert({ id: 95, product_name: 'Potato', price_in_cents: 14 }),
        knex.raw('ALTER SEQUENCE products_id_seq RESTART WITH 96')
      ]);
    });
};
